config/routes.rb
Rails.application.routes.draw do
  get 'rojikarus/index'
  devise_for :users
  root to: 'bookmarks#index'
  resources :bookmarks, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:index, :show, :create, :destroy]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :url, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :sec,      presence: true
  validates :sentence, presence: true

  belongs_to :bookmark
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']  # 環境変数を読み込む記述に変更
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookmark = Bookmark.new
  end

  def create
    # 空の入力ならトップページへ。
    url = params[:bookmark][:url]
    if url.empty? || url.index("youtu") == nil
      redirect_to root_path
      return
    end

    url_id = extract_id(url)

    # 短縮URLなら通常のURLに変換
    if url.index("youtu.be")
      url = "https://www.youtube.com/watch?v=" + url_id
    end

    # 入力されたURLが既にあればそのページへ転送、
    Bookmark.all.each do |bookmark|
      if bookmark[:url] == url_id && bookmark.user.id == current_user.id
        redirect_to bookmark_path(bookmark.id)
        return
      end
    end
    # 新規ならBookmarkテーブルへ登録後動画視聴ページへ。
    title = get_title(url)
    @bookmark = Bookmark.new(bookmark_params(title))
    @bookmark.save
    redirect_to bookmark_path(@bookmark.id)
  end

  def show
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.user.id != current_user.id
      redirect_to root_path
    else
      @comment = Comment.new
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def get_title (url)
    require "open-uri"
    html = URI.open(url).read
    return html.slice(html.index("<title>")+7...html.index("- YouTube</title>")).strip
  end

  def bookmark_params (title)
    params[:bookmark][:url] = extract_id(params[:bookmark][:url])
    params.require(:bookmark).permit(:url).merge(user_id: current_user.id, title: title)
  end

  def extract_id (url)
    if url.index("youtu.be")
      return url.slice((url.index("be/")+3)...url.length).sub("/", "")
    else
      return url.slice((url.index("v=")+2)...url.index("&"))
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  after_action :touch_bookmark, only: [:create, :destroy]

  def index
    @comments = Bookmark.find(params[:bookmark_id]).comments.order("sec ASC").order("created_at ASC")
  end

  def show
  end

  def create
    params[:sec] = params[:sec].to_i
    @comment = Comment.create(sec: params[:sec], sentence: params[:sentence], bookmark_id: params[:bookmark_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
  end

  private

  def touch_bookmark
    Bookmark.find(params[:bookmark_id]).touch
  end
  # def comment_params
    # params.require(:comment).permit(:sec, :sentence, :bookmark_id)
  # end
end

app/controllers/rojikarus_controller.rb
class RojikarusController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rojikarus_helper.rb
module RojikarusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/index.html.erb
<%= render "/shared/header"%>
<div class="zenbu">
  <div class="karada">
    <div class="buttons">
      <%= form_with model: @bookmark, url: bookmarks_path, local: true do |f| %>
        <%= f.text_field :url, placeholder:"URL: (重複不可）", class: "uraru" %>
        <%= f.submit "GO", class: "button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookmarks/show.html.erb
<script src="https://www.youtube.com/iframe_api"></script>

<%= render "/shared/header" %>

<script>
// my funcs
String.prototype.replaceAll = function (a, b) {
  return this.split(a).join(b);
};
function intoSec (times) {
  if (times.indexOf(" ") != -1) {
    times = times.split(" ")[0];
  };
  times = times.split(":"), ret = 0
  if (times.length == 2) {
    return parseInt(times[0]) * 60 + parseInt(times[1]);
  } else {
    return parseInt(times[0]) * 3600 + parseInt(times[1]) * 60 + parseInt(times[2]);
  }
}


// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement('script');

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var player;
function onYouTubeIframeAPIReady() {
  screenHeight = window.screen.height;
  screenWidth = window.screen.width;
  maybePC = screenHeight < screenWidth;
  player = new YT.Player('player', {
    height: 360,
    width: 640,
    videoId: '<%= @bookmark.url %>',
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}

// 4. The API will call this function when the video player is ready.
function onPlayerReady(event) {
  //player.playVideo();
}

// 5. The API calls this function when the player's state changes.
//    The function indicates that when playing a video (state=1),
//    the player should play for six seconds and then stop.
function onPlayerStateChange(event) {
}


window.addEventListener('load', () => {
  const honhe = document.getElementById("honhe").contentWindow;

  // ウィンドウのロードに成功した場合コメント投稿部を表示する＆時限式リロードを停止する
  honhe.document.getElementById("comment_sita").style.display = "inline";
  clearInterval(ticktack);

  // タイムスタンプ部にジャンプ機能を付与
  var hhmms = [], tmp = honhe.document.getElementsByTagName("div");
  for (var i = 0; i < tmp.length; i++) {
    if (tmp[i].className == "hhmm") {
      hhmms.push(tmp[i])
    };
  };
  for (var i = 0; i < hhmms.length; i++) {
    (function(i){
      var theid = hhmms[i].id;
      var hm = intoSec(hhmms[i].innerText);
      hhmms[i].addEventListener("click", () => {
        player.seekTo(hm)
      })
    })(i);
  }

  // コメント投稿機能
  const submit = honhe.document.getElementById("sendbutton");
  submit.addEventListener("click", (e) => {
    e.preventDefault();
    const sentence = honhe.document.getElementById("sentence")
    if (sentence.value != '') {
      const sec = honhe.document.getElementById("sec");
      sec.value = player.getCurrentTime();
      const komeran = honhe.document.getElementById("comment_ue");
      const escaped_sentence = sentence.value.replaceAll("<", "＜").replaceAll(">", "＞")

      timeid = "t" + timefmt(sec.value).replaceAll(":", "_");
      divs = `<div class='timesentence'><div class='hhmm' id='${timeid}'>${timefmt(sec.value)}</div>&nbsp;<div class='kome' id='${timeid}_sentence'>${escaped_sentence}</div></div>`;
      komeran.insertAdjacentHTML("beforeend", divs);
      //最下部にスクロール
      komeran.scrollTo(0, komeran.scrollHeight)

      honhe.document.getElementById("comment_form").submit();
    };
    sentence.value = "";
  });
});

function timefmt (s) {
  s = parseInt(s);
  return parseInt(s / 3600) + ":" + zfill(parseInt(s % 3600 / 60)) + ":" + zfill(parseInt(s % 60))
}

function zfill (n) {
  if (n < 10) {
    return "0" + String(n);
  } else {
    return String(n);
  }
}

var cnt = 0, timeLimit = 2;
var ticktack = setInterval(function(){
  if (cnt++ >= timeLimit){
    location.reload();
  }
}, 1000);

</script>


<div class="showtime">
  <div class="moviefield">
    <div class="ytmovie">
      <div id="player" allow=""></div>
    </div>
    <div class="reloadplz" hidden>動画プレイヤーが表示されないときはページをリロードしてください（自動リロード機能試験運用中）</div>
  </div>
  <div class="commentfield" id="commentfield">
    <iframe frameborder="0" id="honhe" class="honhe" src=<%=bookmark_comments_path(@bookmark.id)%>>
  </div>
</div>

app/views/comments/index.html.erb
<% def timefmt (s) %>
  <% return (s / 3600).to_i.to_s + ":" + zfill((s % 3600 / 60).to_i) + ":" +  zfill((s % 60).to_i) %>
<% end %>

<% def zfill (s) %>
  <% if s < 10 %>
    <% return "0" + s.to_s %>
  <% else %>
    <% return s.to_s %>
  <% end %>
<% end %>

<% def to_id (s)%>
  <% s = timefmt(s) %>
  <% s = s.gsub(":", "_") %>
  <% return "t" + s%>
<% end %>

<script>
window.addEventListener('load', () => {
  const deletebuttons = document.getElementsByClassName("deletekome");
  <% Bookmark.find(params[:bookmark_id]).comments.length.times do |i| %>
    deletebuttons[ <%= i %> ].addEventListener("click", () => {
      document.getElementsByClassName("timesentence")[ <%= i %> ].innerHTML = "";
    });
  <% end %>
  var komeran = document.getElementById("comment_ue");
  komeran.scrollTo(0, komeran.scrollHeight);
});
</script>

<div class="komento">
  <div class="comment_ue" id="comment_ue">
    <% if @comments.length != 0 %>
        <% i = 0 %>
        <% @comments.each do |comment| %>
          <div class="timesentence" id="timesentence<%= i %>">
            <div class='hhmm' id='<%= to_id(comment[:sec]) + "(#{i})" %>'>
              <%= timefmt(comment[:sec]) %>
            </div>
            &nbsp;
            <div class='kome' id='<%= to_id(comment[:sec]) + "(#{i})" %>_sentence'>
              <%= h comment[:sentence] %>
            </div>
            <%= link_to "x", bookmark_comment_path(params[:bookmark_id], comment.id), method: :delete, data: {confirm: "このコメントを削除しますか？"}, class: "deletekome", id: "delebtebutton#{i}" %>
          </div>
          <% i += 1 %>
        <% end %>
    <% else %>
      <%= "コメントを投稿してください" %>
    <% end %>
  </div>
  <div class="comment_sita" id="comment_sita" hidden>
    <%= form_with model: @comment, id: "comment_form", class: "comment_form" do |f| %>
      <%= f.hidden_field :sec %>
      <%= f.hidden_field :bookmark_id, value: @bookmark_id %>
      <%= f.text_field :sentence, placeholder:"コメント", id: "sentence", class: "sentence" %>
      <%= f.submit "送信", id: "sendbutton", class: "button" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manabe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rojikarus/index.html.erb
<div id="panels" class="panels"></div>

<script>
  const panel = '<div class="panel">', line = '<div class="line">', numbers = '<div class="numbers">';
  const toji = '</div>', nums = "０１２３４５６７８９", panels = document.getElementById("panels");
  var ret = "";
  const add = function (s) {
    ret += s;
  };

  for (var i = 0; i < 2; i++) {
    add(panel);
    add(line);
    for (var j = 0; j < 10; j++) {
      add(numbers);
      add('<div id="num' + i + j + '" class="number">');
      add(nums[j]);
      add(toji);
      add(toji);
      if (j % 3 == 2) {
        add(toji);
        add(line);
      }
      if (j == 9) {
        add('<div class="reset"><div id="resetbutton' + i + '" class="resetbutton">リセット</div></div>')
      }
    };
    add(toji);
    add(toji);
  };
  panels.innerHTML = ret;



  var kieru = function (){
    this.style.visibility = "hidden";
  }
  var reset0 = function () {
    if (window.confirm("左のパネルをリセットしますか？")) {
      for (var i = 0; i < 10; i++) {
        document.getElementById("num0" + i).style.visibility = "visible";
      };
    };
  };
  var reset1 = function () {
    if (window.confirm("右のパネルをリセットしますか？")) {
      for (var i = 0; i < 10; i++) {
        document.getElementById("num1" + i).style.visibility = "visible";
      };
    };
  };

  for (var i = 0; i < 2; i++) {
    for (var j = 0; j < 10; j++) {
      document.getElementById("num" + i + j).addEventListener('click', kieru)
    }
  }

  document.getElementById("resetbutton0").addEventListener('click', reset0);
  document.getElementById("resetbutton1").addEventListener('click', reset1);


</script>

app/views/shared/_header.html.erb
<div class="atama">
  <div class="hidari">
    <div class="rogo">
      <%= link_to "Manabe", root_path %>
    </div>
  </div>
  <div class="migis">
    <% if user_signed_in? %>
      <%= link_to current_user.nickname + "のブックマーク", user_path(current_user.id), class: "migi" %>
      <%= link_to "Youtube(別窓)", "https://www.youtube.com/", target: :_blank, rel: "noopener noreferrer", class: "migi" %><br>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "migi" %>
      <%= link_to "rojikaru", rojikarus_index_path, class: "migi" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: "migi" %>
      <%= link_to "新規登録", new_user_registration_path, class: "migi" %>
      <%= link_to "rojikaru", rojikarus_index_path, class: "migi" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<% def time_ago (s) %>
  <% minute_sec = 60 %>
  <% hour_sec = minute_sec * 60 %>
  <% day_sec = hour_sec * 24 %>
  <% week_sec = day_sec * 7 %>
  <% month_sec = day_sec * 30 %>
  <% year_sec = day_sec * 365 %>
  <% now = Time.new %>
  <% sub = now - s %>
  <% if sub > year_sec %>
    <% return (sub / year_sec).to_i.to_s + "年前" %>
  <% elsif sub > month_sec %>
    <% return (sub / month_sec).to_i.to_s + "か月前" %>
  <% elsif sub > week_sec %>
    <% return (sub / week_sec).to_i.to_s + "週間前" %>
  <% elsif sub > day_sec %>
    <% return (sub / day_sec).to_i.to_s + "日前" %>
  <% elsif sub > hour_sec %>
    <% return (sub / hour_sec).to_i.to_s + "時間前" %>
  <% elsif sub > minute_sec %>
    <% return (sub / minute_sec).to_i.to_s + "分前" %>
  <% else %>
    <% return sub.to_i.to_s + "秒前" %>
  <% end %>
<% end %>

<% def timefmt (s) %>
  <% return (s / 3600).to_i.to_s + ":" + zfill((s % 3600 / 60).to_i) + ":" +  zfill((s % 60).to_i) %>
<% end %>

<% def zfill (s) %>
  <% if s < 10 %>
    <% return "0" + s.to_s %>
  <% else %>
    <% return s.to_s %>
  <% end %>
<% end %>

<% def get_comments_list (bookmark_id) %>
  <% ret = "" %>
  <% comments = Bookmark.find(bookmark_id).comments %>
  <% comments.each do |comment| %>
    <% ret += timefmt(comment.sec) %>
    <% ret += " " %>
    <% ret += comment.sentence %>
    <% ret += " \n" %>
  <% end %>
  <% return ret.length == 0 ? "なし" : ret %>
<% end %>

<h1>ブックマークリスト</h1>
<% if @user.bookmarks %>
  <ul>
    <% @user.bookmarks.each do |bookmark| %>
      <li class="bukuma">
        <div class="samunehidari">
          <div>
            <%= link_to "×", bookmark_path(bookmark.id), method: :delete, data: {confirm: "このブックマークを削除しますか？"}, class: "deletebukuma" %>
          </div>
          <div>
            <%= link_to "米コピー", "javascript:alert('" + get_comments_list(bookmark.id) + "');", class: "deletebukuma" %>
          </div>
        </div>
        <div class="samune">
          <img src="https://i.ytimg.com/vi/<%= bookmark.url %>/hqdefault.jpg" width="100">
        </div>
        <div class="bukuma_setumei">
          <div class="taitoru">
            <%= link_to bookmark.title, bookmark_path(bookmark.id) %>
          </div>
          <div class="sonota">
            <%= time_ago(bookmark.created_at) %>作成 (<%= l bookmark.created_at %>)
            <% if bookmark.created_at != bookmark.updated_at %>
              <br><%= time_ago(bookmark.updated_at) %>更新 (<%= l bookmark.updated_at %>)
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <%= "empty" %>
<% end %>